CURRENCY_CODES = {
    "AFN": "Afghani",
    "ALL": "Lek",
    "DZD": "Algerian Dinar",
    "AOA": "Kwanza",
    "ARS": "Argentine Peso",
    "AMD": "Armenian Dram",
    "AWG": "Aruban Florin",
    "AZN": "Azerbaijanian Manat",
    "BSD": "Bahamian Dollar",
    "BHD": "Bahraini Dinar",
    "BDT": "Taka",
    "BBD": "Barbados Dollar",
    "BYN": "Belarussian Ruble",
    "BZD": "Belize Dollar",
    "BMD": "Bermudian Dollar",
    "BTN": "Ngultrum",
    "BOB": "Boliviano",
    "BOV": "Mvdol",
    "BAM": "Convertible Mark",
    "BWP": "Pula",
    "BRL": "Brazilian Real",
    "BND": "Brunei Dollar",
    "BGN": "Bulgarian Lev",
    "BIF": "Burundi Franc",
    "CVE": "Cabo Verde Escudo",
    "KHR": "Riel",
    "CAD": "Canadian Dollar",
    "KYD": "Cayman Islands Dollar",
    "CLF": "Unidad de Fomento",
    "CLP": "Chilean Peso",
    "CNY": "Yuan Renminbi",
    "COP": "Colombian Peso",
    "COU": "Unidad de Valor Real",
    "KMF": "Comoro Franc",
    "CDF": "Congolese Franc",
    "CRC": "Costa Rican Colon",
    "EUR": "Euro",
    "CUC": "Peso Convertible",
    "CUP": "Cuban Peso",
    "ANG": "Netherlands Antillean Guilder",
    "CZK": "Czech Koruna",
    "XOF": "CFA Franc BCEAO",
    "DKK": "Danish Krone",
    "DJF": "Djibouti Franc",
    "XCD": "East Caribbean Dollar",
    "DOP": "Dominican Peso",
    "USD": "US Dollar",
    "EGP": "Egyptian Pound",
    "SVC": "El Salvador Colon",
    "XAF": "CFA Franc BEAC",
    "ERN": "Nakfa",
    "ETB": "Ethiopian Birr",
    "FKP": "Falkland Islands Pound",
    "FJD": "Fiji Dollar",
    "XPF": "CFP Franc",
    "GMD": "Dalasi",
    "GEL": "Lari",
    "GHS": "Ghana Cedi",
    "GIP": "Gibraltar Pound",
    "GTQ": "Quetzal",
    "GBP": "Pound Sterling",
    "GNF": "Guinea Franc",
    "GYD": "Guyana Dollar",
    "HTG": "Gourde",
    "AUD": "Australian Dollar",
    "HNL": "Lempira",
    "HKD": "Hong Kong Dollar",
    "HUF": "Forint",
    "ISK": "Iceland Krona",
    "INR": "Indian Rupee",
    "IDR": "Rupiah",
    "XDR": "SDR (Special Drawing Right)",
    "IRR": "Iranian Rial",
    "IQD": "Iraqi Dinar",
    "ILS": "New Israeli Sheqel",
    "JMD": "Jamaican Dollar",
    "JPY": "Yen",
    "JOD": "Jordanian Dinar",
    "KZT": "Tenge",
    "KES": "Kenyan Shilling",
    "KPW": "North Korean Won",
    "KRW": "Won",
    "KWD": "Kuwaiti Dinar",
    "KGS": "Som",
    "LAK": "Kip",
    "LBP": "Lebanese Pound",
    "LSL": "Loti",
    "ZAR": "Rand",
    "LRD": "Liberian Dollar",
    "LYD": "Libyan Dinar",
    "CHF": "Swiss Franc",
    "MOP": "Pataca",
    "MGA": "Malagasy Ariary",
    "MWK": "Kwacha",
    "MYR": "Malaysian Ringgit",
    "MVR": "Rufiyaa",
    "MRU": "Ouguiya",
    "MUR": "Mauritius Rupee",
    "XUA": "ADB Unit of Account",
    "MXN": "Mexican Peso",
    "MXV": "Mexican Unidad de Inversion (UDI)",
    "MDL": "Moldovan Leu",
    "MNT": "Tugrik",
    "MAD": "Moroccan Dirham",
    "MZN": "Mozambique Metical",
    "MMK": "Kyat",
    "NAD": "Namibia Dollar",
    "NPR": "Nepalese Rupee",
    "NZD": "New Zealand Dollar",
    "NIO": "Cordoba Oro",
    "NGN": "Naira",
    "NOK": "Norwegian Krone",
    "OMR": "Rial Omani",
    "PKR": "Pakistan Rupee",
    "PAB": "Balboa",
    "PGK": "Kina",
    "PYG": "Guarani",
    "PEN": "Nuevo Sol",
    "PHP": "Philippine Peso",
    "PLN": "Zloty",
    "QAR": "Qatari Rial",
    "MKD": "Denar",
    "RON": "Romanian Leu",
    "RUB": "Russian Ruble",
    "RWF": "Rwanda Franc",
    "SHP": "Saint Helena Pound",
    "WST": "Tala",
    "STN": "Dobra",
    "SAR": "Saudi Riyal",
    "RSD": "Serbian Dinar",
    "SCR": "Seychelles Rupee",
    "SLE": "Leone",
    "SGD": "Singapore Dollar",
    "XSU": "Sucre",
    "SBD": "Solomon Islands Dollar",
    "SOS": "Somali Shilling",
    "SSP": "South Sudanese Pound",
    "LKR": "Sri Lanka Rupee",
    "SDG": "Sudanese Pound",
    "SRD": "Surinam Dollar",
    "SZL": "Lilangeni",
    "SEK": "Swedish Krona",
    "CHE": "WIR Euro",
    "CHW": "WIR Franc",
    "SYP": "Syrian Pound",
    "TWD": "New Taiwan Dollar",
    "TJS": "Somoni",
    "TZS": "Tanzanian Shilling",
    "THB": "Baht",
    "TOP": "Pa’anga",
    "TTD": "Trinidad and Tobago Dollar",
    "TND": "Tunisian Dinar",
    "TRY": "Turkish Lira",
    "TMT": "Turkmenistan New Manat",
    "UGX": "Uganda Shilling",
    "UAH": "Hryvnia",
    "AED": "UAE Dirham",
    "USN": "US Dollar (Next day)",
    "UYI": "Uruguay Peso en Unidades Indexadas (URUIURUI)",
    "UYU": "Peso Uruguayo",
    "UZS": "Uzbekistan Sum",
    "VUV": "Vatu",
    "VED": "Bolivar",
    "VND": "Dong",
    "YER": "Yemeni Rial",
    "ZMW": "Zambian Kwacha",
    "ZWL": "Zimbabwe Dollar",
}


def is_valid_currency_pair(literal: str) -> bool:
    """
    Check if a folder name can be split into exactly two valid 3-char words from the dictionary.
    """
    literal = literal.upper()
    if len(literal) != 6:
        return False
    return literal[:3] in CURRENCY_CODES and literal[3:] in CURRENCY_CODES
